# Site settings
title: yotzincortes.com
email: yotzin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Right here, right now.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yotzincortes.github.io" # the base hostname & protocol for your site
twitter_username: yotzin
github_username:  YotzinCortes

# Build settings
markdown: kramdown
